### ISSUE TITLE
平板上popup弹出框无法关闭

### ISSUE THREAD

**Issue by pipiliang** [rdkmaster/jigsaw#106]
浏览器：海豚浏览器
测试设备：ipad
异常说明：tracing-event alert弹出框，在点击OK和关闭图标后无反应。

**Comment by rdkmaster** [comment]
谢谢，这套组件集主要是面对PC端的，移动端我们近期还没计划支持。

**Comment by rdkmaster** [comment]
see <https://github.com/rdkmaster/jigsaw/pull/123>
