### ISSUE TITLE
OnPush改造测试问题汇总

### ISSUE THREAD

**Issue by 10229428** [rdkmaster/jigsaw#1064]
- breadcrumb：使用路由导航数据，输入属性routesConfig绑定变量routers，如果只改变routers里面某个元素的某个属性值的时候，页面不会变；

- dialog：输入属性buttons绑定变量，一个数组，在对话框弹出之后，如果只改变绑定的buttons对象中，某个属性值，比如某个按钮的label、删除某个元素，或者增加一个，都不生效。除非是将整个变量重新赋值；

- cascade: 无法动态修改设置过的data值（这个好像原来就有问题）；

- slider： mark绑定之后，无法通过修改绑定变量的属性或者增删元素来实现动态修改，只能重新赋值才能生效

**Comment by 10229428** [comment]
- button-bar、tile-lite、radio-lite、list-lite: 修改绑定data属性的变量，在原变量上操作不生效（包括增删元素、修改对象数组中某个对象的属性），重新赋值可以改变。
    感觉这应该是个共性问题：这几个组件中，均存在模板中使用ngFor遍历data属性。

- transfer未看到有修改OnPush的代码？

- alert: 对于弹出自定义的alert框，无法动态修改buttons（有点像dialog），另外自定义弹出alert，貌似没法修改弹出框的宽度，设置width无效（不确定自定义弹出alert是否有实际用途）

**Comment by zcg8633** [comment]
输入属性如果是对象或数组，修改其中的属性值，或者数组增删改，不会改变这个属性的引用，不会引起onpush检测。这种变化可以由doCheck捕获到，在doCheck执行手动变更检查，界面会跟着变化，但是doCheck对性能的影响可能会更大

**Comment by 10229428** [comment]
breadcrumb：	未修改OnPush时，同样无法更新
slider： 未修改OnPush时，同样无法更新

dialog、alert：未修改OnPush时，对buttons的修改，可以直接生效；改为OnPush之后，增加ngDoCheck可以生效

button-bar、tile-lite、radio-lite、list-lite：未修改OnPush时，对datas的修改，可以直接生效；改为OnPush之后，增加ngDoCheck可以生效

cascade：未修改OnPush时，修改label可以直接生效，增删元素不行；改为OnPush之后，修改label和增删元素都不行，但是增加ngDoCheck之后，修改label可以生效
