### ISSUE TITLE
关于j-navigation-menu组建设置showToggleButton指令的问题

### ISSUE THREAD

**Issue by mimiyoo** [rdkmaster/jigsaw#1250]
当j-navigation-menu 设置 [showToggleButton]="false"后通过设置[collapsed]="true"后不能正常折叠，错误如下图：
![image](https://user-images.githubusercontent.com/25876258/89105135-2c5db680-d451-11ea-993a-141157a0e350.png)

**Comment by mimiyoo** [comment]
如下为未折叠截图：
![image](https://user-images.githubusercontent.com/25876258/89105186-8b233000-d451-11ea-8bb1-5c44059aafc2.png)

**Comment by rdkmaster** [comment]
@10229428 周庆看看这个问题

https://gitlab.zte.com.cn/10045812/ng-eval/issues/2067
