### ISSUE TITLE
Drag&Drop中table-drag拖拽换行功能不太合理

### ISSUE THREAD

**Issue by 10222927** [rdkmaster/jigsaw#210]
![table-drag](https://user-images.githubusercontent.com/30395891/30771409-ccfcb0f0-a079-11e7-911d-eec79ed7912c.gif)
图片描述：将table第一行拖拽到第二行，此时第二行上边沿显示蓝色，默认第一行已经拖拽到第二行范围内，可以交换位置，但实际情况不能。
然后，将第一行拖拽到第三行，效果是第一行与第二行交换位置。

**Comment by 10222927** [comment]
![table-drag](https://user-images.githubusercontent.com/30395891/30771431-67cac068-a07a-11e7-85f1-6c38e46a3b35.gif)

**Comment by hpyou** [comment]
@10222927 那个提示线表示拖动行拖动到的位置，‘第二行上边沿显示蓝色’ 表示拖动行将放在第二行的上面，本来第一行就在上面，所以不动
