### ISSUE TITLE
j-radios的value属性并没有实现双向绑定，当组件中属性变动后单选的界面没有变化

### ISSUE THREAD

**Issue by 6933** [rdkmaster/jigsaw#239]
j-radios的value属性并没有实现双向绑定，当组件中属性变动后单选的界面没有变化

**Comment by hpyou** [comment]
@6933 请检查j-radios中有没有配`trackItemBy`, 或者`value`与j-radio-option的遍历项是否一致

**Comment by 6933** [comment]
代码如下：
	<j-radios [(value)]="selectedCity" trackItemBy="id"   (valueChange)="radioChange($event)">
		<j-radio-option *ngFor="let item of citys" [value]="item">
			{{item.id}}-{{item.name}}
		</j-radio-option>
	</j-radios>
经测试： value绑定的selectedCity是对citys中一项的引用。 
用：     this.selectedCity=this.citys[4]  界面上会同步变化 
问题：能否双向绑定到一个简单类型上？如:
city_id:number;
或 city_id:string

**Comment by rdkmaster** [comment]
`citys`这个数组支持给一个字符串数组，这样j-radio的value属性就支持双绑到简单的值上了。

**Comment by rdkmaster** [comment]
先关掉，有疑问请随时重开这个issue
