### ISSUE TITLE
表格表头FF，CHROME显示样式不一致

### ISSUE THREAD

**Issue by rdkmaster** [rdkmaster/jigsaw#32]
![image](https://user-images.githubusercontent.com/16191626/27281841-32b6dc68-5520-11e7-999a-ec084396b7df.png)

![image](https://user-images.githubusercontent.com/16191626/27281843-36e0f440-5520-11e7-98d3-eb10bfd5882c.png)

**Comment by hpyou** [comment]
has been fixed when in gitlab
