### ISSUE TITLE
input上直接加style导致ui异常

### ISSUE THREAD

**Issue by rdkmaster** [rdkmaster/jigsaw#335]
代码为
```
编辑tooltip
<jigsaw-input style="padding-top: 40px" width="370" [(value)]="tooltipMessage">
</jigsaw-input>

<br>

<jigsaw-button width="180px" [jigsawTooltip]="tooltipMessage">
    鼠标挪到这里显示tooltip
</jigsaw-button>
```

效果为

![image](https://user-images.githubusercontent.com/16191626/33541634-bf75916c-d90a-11e7-9aca-b8ad79d462ec.png)

**Comment by 10222927** [comment]
margin-top 就不会导致异常，padding-top应该是说内部的input 距离外部jigsaw-input 的距离，直接把input 给挤扁了

**Comment by 10222927** [comment]
input.scss中host: padding: 0 !important;  直接不给用户设置padding, 不知道合不合理。

**Comment by hpyou** [comment]
内边距会挤掉里面的内容
