### ISSUE TITLE
combo 里的options是jigsaw-tile,button或者collapse时，下拉菜单会异常关闭。注意jigsaw-tile，详见图3

### ISSUE THREAD

**Issue by 10222927** [rdkmaster/jigsaw#364]
![combo1](https://user-images.githubusercontent.com/30395891/33815075-b155eeec-de69-11e7-9e9d-e3795de5a74e.gif)
![combo2](https://user-images.githubusercontent.com/30395891/33815088-c7783f9a-de69-11e7-8ca4-36cba248ed41.gif)

**Comment by 10222927** [comment]
鼠标从外边移入combo-select,然后点击combo-select 里的options ,会出现异常关闭。
有时不会出现异常，可重复上述步骤。点击options若干次，次数随机。

**Comment by 10222927** [comment]
![combo3](https://user-images.githubusercontent.com/30395891/33821758-0dc7424a-de90-11e7-8022-a68cb1c59af7.gif)
图3
当combo-select是多选时，多次点击options，仍会异常关闭。

**Comment by rdkmaster** [comment]
故障无法浮现
