### ISSUE TITLE
【IE11】drag-drop功能异常，table-drag demo控制台报错

### ISSUE THREAD

**Issue by weboey** [rdkmaster/jigsaw#383]
测试URL：http://localhost:4201/drag-drop/table-drag

![ie11-drag-drop-table-drag](https://user-images.githubusercontent.com/14002656/33973127-2d1db92a-e0bc-11e7-8d1b-cd3e1b72f96e.gif)

**Comment by 10222927** [comment]
IE11 不支持setDragImage方法。
拟解决：用方法判断当前浏览器是否为IE，如果是不调用setDragImage方法。
目前找不到好的判断方法。

**Comment by 10222927** [comment]
IE11拖拽的时候，会触发三个事件jigsawDragOver，jigsawDragLeave，jigsawDrop，但是IE11 触发的是<jigsaw-table>上的事件，正确的应该触发div.option-box上的三个事件。
IE11里拖拽换行，鼠标操作div.option-box这一元素over，leave,drop一行时，一直调用<jigsaw-table>上的事件

**Comment by 10222927** [comment]
换种说法：IE11里拖拽换行，在触发jigsawDragOver，jigsawDragLeave，jigsawDrop三个事件时，拖拽的元素CSS是jigsaw-table-host,本应该是CSS是option-box的元素

**Comment by hpyou** [comment]
这个问题和 #358 结合起来一起看

**Comment by 10222927** [comment]
#358  是因为IE11 不支持setDragImage方法。不调用这个方法，拖拽就会正常

**Comment by hpyou** [comment]
你先看下，能不能有个兼容的方法，实在不行先放放
