### ISSUE TITLE
Table组件sortable功能有异常，表格不是多级排序应该不能同时高亮两列排序状态，并且初始的默认排序没有生效

### ISSUE THREAD

**Issue by weboey** [rdkmaster/jigsaw#394]
测试URL：http://localhost:4201/table/sortable

![table-03](https://user-images.githubusercontent.com/14002656/33988173-908b5642-e0fe-11e7-964b-ddf8167a4a68.jpg)

**Comment by rdkmaster** [comment]
> Table组件sortable功能有异常，表格不是多级排序应该不能同时高亮两列排序状态
这个是已知故障，见https://github.com/rdkmaster/jigsaw/issues/333

> 并且初始的默认排序没有生效
这个是需求，见https://github.com/rdkmaster/jigsaw/issues/297
