### ISSUE TITLE
[firefox]table的自动计算列宽不符合预期

### ISSUE THREAD

**Issue by hpyou** [rdkmaster/jigsaw#402]
在chrome和ie中，这时符合预期的：
![image](https://user-images.githubusercontent.com/15992591/34089117-f0052c5a-e3e8-11e7-836b-71c0350d17c6.png)

在firefox中：
![image](https://user-images.githubusercontent.com/15992591/34089132-0f09ad74-e3e9-11e7-9662-de1921c09ed4.png)

**Comment by rdkmaster** [comment]
火狐的兼容性，暂时降低优先级，优先修复IE11 的兼容性
