### ISSUE TITLE
【ie 11】button/disabled 鼠标点击CheckBox，出现异常状态

### ISSUE THREAD

**Issue by 10222927** [rdkmaster/jigsaw#405]
![ie11_disabled](https://user-images.githubusercontent.com/30395891/34099493-9efd2042-e41a-11e7-804d-756d0d2597bb.gif)
鼠标点一下，checkbox 四周边框黑线出现，但是box没有打上勾，这个button已经处于disabled状态。

**Comment by 10222927** [comment]
其实checkbox已经打钩，button也变成disabled状态，只需要切换窗口或者放大缩小窗口，表现就会正常。

**Comment by hpyou** [comment]
这个与ie11的渲染有关系，可以和这个issue #354 一起看

**Comment by 10222927** [comment]
问题已找到，如果.jigsaw-button-disabled { }中color的值是普通的black，red，yellow,或者 #008fd4，#ffcc66， rgba(#000,1)等颜色，不会出现上述问题。但是一旦用rgba(#000,0.4)等透明度不为1的，都会出现问题。

**Comment by hpyou** [comment]
应该不是这个原因吧，你可以看下table的checkbox是可以显示的
