### ISSUE TITLE
CI上，loading组件的用例依然有偶尔失败的现象

### ISSUE THREAD

**Issue by rdkmaster** [rdkmaster/jigsaw#416]
![image](https://user-images.githubusercontent.com/16191626/34284961-cc825796-e710-11e7-91be-99b5760518ff.png)

**Comment by 10222927** [comment]
组件jigsaw-bubble-loading只存在3秒，此处验证存在会出现不稳定。和之前#413相同

**Comment by rdkmaster** [comment]
那把时间改长一些，5s或者10s，让这个用例可以稳定

**Comment by 10222927** [comment]
这里我点击了以后，jigsaw-bubble-loading一定会出现（这在前面的不限时的情况下，已经验证过，只不过这里是全局的弹出），我这里就是等待他消失。存在—>消失 ，应该可以验证jigsaw-bubble-loading在限定时间内正常。
