### ISSUE TITLE
【IE11】list 和comboselect配合使用，体验很差

### ISSUE THREAD

**Issue by 10222927** [rdkmaster/jigsaw#433]
详见/list/full，最后一个list。
可能和 #354 是同一个问题，但是好像不太一样

**Comment by rdkmaster** [comment]
我zhl这里看上去，感觉还可以

![aa](https://user-images.githubusercontent.com/16191626/34410445-62098bf0-ec0b-11e7-9007-2e3bc21a6c4d.gif)

**Comment by rdkmaster** [comment]
会不会是你的云桌面导致的？

**Comment by 10222927** [comment]
我本地IE也是好的，出现体验不好应该是特例
