### ISSUE TITLE
TableData的fromAjax使用HttpClientOptions配置POST请求，疑似没有实现

### ISSUE THREAD

**Issue by hpyou** [rdkmaster/jigsaw#451]
![image](https://user-images.githubusercontent.com/15992591/34553421-63d21144-f162-11e7-80a3-f7fdb382df08.png)

![image](https://user-images.githubusercontent.com/15992591/34553451-7f7e4eda-f162-11e7-81d2-fb7fdcd715e1.png)

**Comment by rdkmaster** [comment]
post方法的话，不能使用`params`属性，要用`body`属性

**Comment by hpyou** [comment]
ok, fixed
