### ISSUE TITLE
j-list组件的样式vertical-align会对外部有影响

### ISSUE THREAD

**Issue by rdkmaster** [rdkmaster/jigsaw#474]
<div style="height:380px; margin-top:6px;">
        <jigsaw-list height="100%" width="150px" (selectedItemsChange)="onRegionSelected($event)">
            <jigsaw-list-option *ngFor="let region of regions" [value]="region">
            </jigsaw-list-option>
        </jigsaw-list>
        <jigsaw-list height="100%" width="200px" [multipleSelect]="true" [(selectedItems)]="selectedKPIs">
            <jigsaw-list-option *ngFor="let kpi of kpis" [value]="kpi">
            </jigsaw-list-option>
        </jigsaw-list>
        <div style="display: inline-block; width: 177px; height: 100%; border: solid #ccc 1px; border-radius: 2px">
            <jigsaw-tag *ngFor="let kpi of selectedKPIs">{{kpi.label}}</jigsaw-tag>
        </div>
    </div>

![image](https://user-images.githubusercontent.com/16191626/35788327-2ff538f8-0a6f-11e8-878e-a5fb0655ae68.png)

**Comment by hpyou** [comment]
行内元素的vertical-align默认是baseline，jigsaw组件的inline-block默认设置了vertical-align: middle，主要是为了垂直方向布局的方便。
