### ISSUE TITLE
input无法通过拖动选择文本

### ISSUE THREAD

**Issue by rdkmaster** [rdkmaster/jigsaw#56]
http://rdk.zte.com.cn:4200/demo/tabs/dynamicTab

![image](https://user-images.githubusercontent.com/16191626/27572230-434fdd18-5b3d-11e7-9e36-f48ceceb641b.png)

**Comment by zhongzhong0505** [comment]
我试了下可以啊

**Comment by rdkmaster** [comment]
那可能是我用的是老版本上测的，一会看看没有存在的话就关掉了。
