### ISSUE TITLE
combo的服务端查询现在是输入一个字母输入框就disabled

### ISSUE THREAD

**Issue by hpyou** [rdkmaster/jigsaw#594]

**Comment by hpyou** [comment]
![gif](https://user-images.githubusercontent.com/15992591/37652486-a3ce0aa6-2c76-11e8-84ac-bccb8a112a7c.gif)

**Comment by rdkmaster** [comment]
如果需要约束关键字的最短长度，可以修改demo代码里的如下部分

```
    handleSearching(filterKey, data) {
        filterKey = filterKey ? filterKey.trim() : '';
        if (filterKey.length <=3) return; // <- add this line
        data.filter(filterKey, ['enName', 'zhName']);
    }
```

**Comment by hpyou** [comment]
现在是输一个字母就disabled不让输了

**Comment by rdkmaster** [comment]
`data.filter(filterKey, ['enName', 'zhName']);`  
这个`data`是一个`PageableArray`，这个`PageableArray.filter`里头有debounce，300ms写死了。所以要输入的快一些

**Comment by rdkmaster** [comment]
可以把300ms的debounce时间放开作为一个配置项，在人输入的时候，300ms的确有点太快了，500ms差不多
