### ISSUE TITLE
AbstractDialogComponentBase没有输入和输出属性（继承的也没有，但他本身是有的，没显示）

### ISSUE THREAD

**Issue by 10222927** [rdkmaster/jigsaw#622]
http://rdk.zte.com.cn:40080/components/jigsaw/api?apiItem=AbstractDialogComponentBase&parentName=class

![image](https://user-images.githubusercontent.com/30395891/38228300-3d34ba32-3735-11e8-855c-b3ef5c2673cc.png)
![image](https://user-images.githubusercontent.com/30395891/38228318-50e8cc76-3735-11e8-9ac2-eb40bd7bf73a.png)

**Comment by rdkmaster** [comment]
see https://github.com/compodoc/compodoc/issues/529
