### ISSUE TITLE
AjaxCompleteCallback没有普通属性，不该显示

### ISSUE THREAD

**Issue by 10222927** [rdkmaster/jigsaw#627]
http://rdk.zte.com.cn:40080/components/jigsaw/api?apiItem=AjaxSuccessCallback&parentName=class

![image](https://user-images.githubusercontent.com/30395891/38228527-6f1c5dce-3736-11e8-8322-630b1121ea4d.png)

![image](https://user-images.githubusercontent.com/30395891/38228549-8bcb237e-3736-11e8-9d2a-cd16d7a8d47c.png)

**Comment by rdkmaster** [comment]
构造函数中带有public/protected，直接将属性变成了类成员，这是对的。
建议再学习一下ts基本语法
