### ISSUE TITLE
使用Typescript 2.4.1版本编译时rxjs报错

### ISSUE THREAD

**Issue by baxtergu** [rdkmaster/jigsaw#63]
报错信息如下：
![image](https://user-images.githubusercontent.com/2825625/27641241-e6d8e784-5c4d-11e7-9406-224d3ee6e05f.png)
 该错误是rxjs在高版本typescript下的bug，[rxjs/#issue2539](https://github.com/ReactiveX/rxjs/issues/2539)   
解决方案有2个：
- 使用rxjs v6 alpha版本
- 修改node_modules/rxjs/Subject.d.ts文件的第24行的Observable\<T\>为Observable\<any\>临时解决  
![image](https://user-images.githubusercontent.com/2825625/27641491-91d0a1ae-5c4e-11e7-9600-7109a7f879d2.png)
![image](https://user-images.githubusercontent.com/2825625/27641509-a278e1f6-5c4e-11e7-8856-a0aea0bb83a7.png)  
不知道是不是通用问题，我在使用的时候遇到了，在这里分享一下解决方法，希望能有所帮助。 : )

**Comment by rdkmaster** [comment]
现在master分支上的ts版本是2.4但是我们打算暂时回退到2.3.4，因为ts2.4和webstorm有个冲突。。。。
