### ISSUE TITLE
jigsaw-upload组件需要支持一个mode输入属性，用于设置控件的不同状态

### ISSUE THREAD

**Issue by rdkmaster** [rdkmaster/jigsaw#720]
## mode的定义

```
mode: "default" | "button" | "link"
```

分别对应着当前的默认状态，按钮状态和超链状态。

**Comment by hpyou** [comment]
具体修改：
- 现有的上传页和列表页，改成同时显示
- 原来区分单个文件和多个文件显示，现在只有列表显示
- 默认情况改成只有加号，可点击加号，去掉按钮
- 新增点击按钮和超链的形式

**Comment by hpyou** [comment]
https://github.com/rdkmaster/jigsaw/pull/744
