### ISSUE TITLE
select等组件支持修改高度

### ISSUE THREAD

**Issue by hpyou** [rdkmaster/jigsaw#826]

**Comment by hpyou** [comment]
![image](https://user-images.githubusercontent.com/15992591/49719911-7a7cdf80-fc99-11e8-812f-d336cd55e551.png)

默认高度也不匹配
![image](https://user-images.githubusercontent.com/15992591/49719923-88326500-fc99-11e8-8646-92d071f4b0a4.png)

**Comment by rdkmaster** [comment]
所有单行组件，都统一成一个高度吧，包括（可能有漏的）select combo 各种input 按钮默认尺寸

**Comment by rdkmaster** [comment]
要找Ux沟通一下，新皮肤里，这些单行组件的高度需要统一为多少？
