### ISSUE TITLE
抽屉功能扩展

### ISSUE THREAD

**Issue by hpyou** [rdkmaster/jigsaw#837]
- 能停靠在某个容器的边缘，比如某个tab的边缘，而不是只是window；
- 能支持设置抽屉的高度和位置

**Comment by rdkmaster** [comment]
还要支持抽屉抽出来后，占位置和不占位置的功能

**Comment by hpyou** [comment]
### 支持抽屉在容器里展开

添加一个输入属性：
```
@Input()
container: HtmlElement | ComponentRef | string // string是一个样式class
```
逻辑：
主要是寻找父容器的DOM对象，判断父容器是否有定位，如果没有则给这个父容器加上`position: relative`，如果container给的是个组件，则组件必须有公开的属性ElementRef以获取它的DOM对象

修改的部分：
现在的drawer的定位是写死的`fixed`，改成动态的，即有父容器时为`position:absolute`，没有父容器时为`position: fixed`

这样drawer应该可以实现在容器里展开和收缩

### 支持设置高度，外边距

这个应该好弄，主要是操作一些样式

### 支持在文档流中展开

添加一个输入属性:
```
@Input()
mode: 'float' | 'indom' //默认'float' 
```
`indom`模式时，不给drawer设置定位，让其和普通的`block`元素一样。

添加一个输入属性:
```
@Input()
minHeight: number|string
```
用于在dom中默认打开的高度

> 由于drawer是有不同方向的，这边默认打开的有可能是高度或宽度

**Comment by hpyou** [comment]
这个也需要支持：
![image](https://user-images.githubusercontent.com/15992591/50323400-757b2400-0514-11e9-83db-d6d2e6a978b1.png)

**Comment by rdkmaster** [comment]
> ```
> @Input()
> mode: 'float' | 'indom' //默认'float' 
> ```

`indom` 改为 `inline` 吧 

> ```
> @Input()
> minHeight: number|string
> ```

`minHeight` 就叫`height` / `width`

**Comment by rdkmaster** [comment]
如果人家在容器上加了position，并且position的值是static，那就在控制台报错，并且无视floating为true的配置项。position没设，或者是relative/absoulte则就相安无事。

**Comment by hpyou** [comment]
这里需要给容器加个overflow:hidden
