### ISSUE TITLE
搜索功能似乎有问题，涉及到select、combo-select、list-lite

### ISSUE THREAD

**Issue by hpyou** [rdkmaster/jigsaw#953]
![GIF](https://user-images.githubusercontent.com/15992591/60080942-6dba6780-9763-11e9-9f29-9426a9bb7703.gif)

![GIF2](https://user-images.githubusercontent.com/15992591/60080951-6f842b00-9763-11e9-9d77-863ef3813192.gif)

![GIF3](https://user-images.githubusercontent.com/15992591/60080958-73b04880-9763-11e9-8f25-5402565d207c.gif)

**Comment by rdkmaster** [comment]
已经解决。
