### ISSUE TITLE
@ngx-translate/core国际化的问题

### ISSUE THREAD

**Issue by hpyou** [rdkmaster/jigsaw#97]
在ShareModule里面用TranslateModule.forChild会导致translateService与appModule里的不是同一个实例，
用户更改appModule里的语言时，ShareModule里的不会同步更新，这是一个问题。
现在ShareModule里面直接引用TranslateModule，就能同步更新，但这时ShareModule的国际化配置文件就要和AppModule的一致，这是目前的实现方法，用户要用国际化，需要把我们的i18n文件拷到他的工程里面去。

**Comment by hpyou** [comment]
@rdkmaster

**Comment by rdkmaster** [comment]
控件在读国际化词条的时候能不能设定一个默认值？这样子的话，即使用户不设置这些词条他也能够正确的显示默认值。如果能够做到这样的话，那这个方案就可以接受，要不然的话无法接受。
